### PR TITLE
UI Improvements to Projects

### PR DESCRIPTION
**Pull request by pjlasl**
This will bring improvements to Projects. Implementing a visual indication that a project can be purchased.

### CODE REVIEW

**Comment by pjlasl** [comment]
Hope I did this right...

**Comment by N8python** [comment]
You did!

**Comment by N8python** [comment]
This looks good - I'll test it now!

**Comment by N8python** [comment]
One thing - The IQ button isn't displaying correctly. It just says "potatoz", rather than the actual cost to buy one more IQ.

**Review by N8python — CHANGES_REQUESTED** [review]
We need to fix the IQ button.

**Comment by pjlasl** [comment]
I have that fixed locally. I will push as soon as I get home

**Comment by N8python** [comment]
Got it. Thx.

**Review by N8python — DISMISSED** [review]
The IQ button isn't showing now.

**Review by N8python — APPROVED** [review]

**Comment by N8python** [comment]
Everything is working know. Are you ready to merge, pjlasl?

**Comment by pjlasl** [comment]
You can merge at anytime.

**Comment by N8python** [comment]
Okay, let’s merge!

**Comment by pjlasl** [comment]
looks good. let me know if there is anything else you would like done.

**Comment by N8python** [comment]
What you’ve done so far is amazing! I think we’ve (you mostly) added enough updates for now.

**Comment by pjlasl** [comment]
LOL. I tried to focus on the UI and not touch the game's mechanics.

**Comment by N8python** [comment]
You did a great job with that - your UI updates didn’t have any major changes to the core mechanics, though they did enhance the experience tenfold.

**Pull request merged**
