### PR TITLE
Add ui improvements!

### PR DESCRIPTION
**Pull request by N8python**
Add pjlasl's improvements.

### CODE REVIEW

**Comment by N8python** [comment]
I don't know bootstrap, so I'm not sure how I can help. However, I'll be glad to work on anything you want me to - this redesign looks really good!

**Comment by N8python** [comment]
Can I help transfer the rest of the UI to bootstrap?

**Comment by N8python** [comment]
Or maybe there are bugs that I could fix?

**Comment by pjlasl** [comment]
thanks for bringing in my changes :). I haven't brought in the battle portion in the tabs. I was playing thru it

**Comment by pjlasl** [comment]
bootstrap is not difficult to use. You can review here: https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by pjlasl** [comment]
i would strongly recommend you use visual studio code (it free) and with plugins like jshint and gitlens.

**Comment by N8python** [comment]
I'm testing your UI right now! After I'm done with a playthrough, I will merge.

**Comment by pjlasl** [comment]
Cool. Saw you fixed some things to :+1:

**Comment by N8python** [comment]
Thanks! I’m working on a massive commit that fixes 10 different bugs/typos or so.

**Comment by pjlasl** [comment]
Cool. Hope my changes have been satisfactory. Tried focus on UI for you

**Comment by N8python** [comment]
Your changes were more than satisfactory. I loved them! It really showed me how the UI of an incremental game should look! I was wondering, would you mind waiting to commit code for the next thirty minutes or so so I can push my big commit without any conflicts? Thx.

**Comment by pjlasl** [comment]
Please do. I am not home and probably won't do anything until tomorrow. Thanks for the vote of confidence!

**Comment by N8python** [comment]
Got it - We can start working on merging the new UI tomorrow.

**Comment by N8python** [comment]
Pjlasl, would you mind doing a play-through to check for any last bugs?

**Comment by pjlasl** [comment]
I did a merge into my code this morning. Freaked out because I lost most of my ui Changes, then I realized u did do the full UI update LOL. Should I do another merge before I test?

**Comment by pjlasl** [comment]
I'm in a meeting, but I can test after that

**Comment by N8python** [comment]
Got it, thank you!

**Comment by N8python** [comment]
Another merge before you test? If you want to add more to the current GUI, sure!

**Comment by pjlasl** [comment]
how do i merge your latest changes into my branch?

**Comment by pjlasl** [comment]
I am finally getting a chance to test. so far it looks good. i'll update the UI if I find something.

**Comment by N8python** [comment]
Thanks!

**Comment by pjlasl** [comment]
how can i get notified when u post here? LOL.

**Comment by N8python** [comment]
I’m not sure. For me, it always get sent directly to my email.

**Comment by N8python** [comment]
Could you let me know when you have finished testing so I could merge changes? Thx.

**Comment by pjlasl** [comment]
Sorry. I just pushed a couple of fixes. You can merge now

**Comment by N8python** [comment]
Okay - thx for working so hard on the UI and all the bug fixes. Merging now!

**Comment by pjlasl** [comment]
Let me know if you would like anything else. I may play around with the blue buttons to try and make them more uniform if you don't mind

**Comment by N8python** [comment]
Got it - you may have to make a new fork to resolve all the commits I made and to prevent merge conflicts. What you’ve done for me is great and awesome, and I couldn’t ask for more! Thx.

**Comment by pjlasl** [comment]
ok, i figured out how to merge your changes into my fork. getting used to using github.

**Comment by N8python** [comment]
Same here. All the different features take time to learn.

**Comment by pjlasl** [comment]
I updated the buttons, giving them a little more character.

**Comment by N8python** [comment]
Awesome!

**Comment by pjlasl** [comment]
updated projects so that you can identify which one can be clicked on. cursor changes as does the border color

**Comment by N8python** [comment]
Ooh - I will take a look. Maybe open a pull request?

**Comment by pjlasl** [comment]
Ok. Do I pull request from Master or Patch 8?

**Pull request merged**
